apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openstack-operator.openstack-operators: ""
  name: openstack-operator
  namespace: openstack-operators
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: openstack-operator
  source: openstack-operator-index
  sourceNamespace: openstack-operators
